Imports System.Collections.Generic
Imports System.ComponentModel

Namespace Localization
    Public NotInheritable Class LocalizationManager
        Implements INotifyPropertyChanged

        Private Shared ReadOnly _instance As New LocalizationManager()
        Private ReadOnly _translations As Dictionary(Of String, IReadOnlyDictionary(Of String, String))
        Private _currentLanguageCode As String = "en"

        Private Sub New()
            _translations = BuildTranslations()
        End Sub

        Public Shared ReadOnly Property Instance As LocalizationManager
            Get
                Return _instance
            End Get
        End Property

        Default Public ReadOnly Property Item(key As String) As String
            Get
                Return GetString(key, key)
            End Get
        End Property

        Public Property CurrentLanguageCode As String
            Get
                Return _currentLanguageCode
            End Get
            Set(value As String)
                Dim normalized = NormalizeLanguageCode(value)
                If String.Equals(_currentLanguageCode, normalized, StringComparison.OrdinalIgnoreCase) Then
                    Return
                End If

                _currentLanguageCode = normalized
                RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(NameOf(CurrentLanguageCode)))
                RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs("Item[]"))
            End Set
        End Property

        Public Function GetString(key As String, Optional fallback As String = Nothing) As String
            If String.IsNullOrWhiteSpace(key) Then
                Return If(fallback, String.Empty)
            End If

            Dim currentMap As IReadOnlyDictionary(Of String, String) = Nothing
            If _translations.TryGetValue(_currentLanguageCode, currentMap) AndAlso currentMap.ContainsKey(key) Then
                Return currentMap(key)
            End If

            Dim englishMap As IReadOnlyDictionary(Of String, String) = Nothing
            If _translations.TryGetValue("en", englishMap) AndAlso englishMap.ContainsKey(key) Then
                Return englishMap(key)
            End If

            Return If(fallback, key)
        End Function

        Public Shared Function NormalizeLanguageCode(value As String) As String
            Dim normalized = If(value, String.Empty).Trim().ToLowerInvariant()
            If normalized.StartsWith("zh", StringComparison.Ordinal) Then
                Return "zh-CN"
            End If

            Return "en"
        End Function

        Public Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged

        Private Shared Function BuildTranslations() As Dictionary(Of String, IReadOnlyDictionary(Of String, String))
            Dim en = New Dictionary(Of String, String)(StringComparer.OrdinalIgnoreCase) From {
                {"App.Name", "MediaFactory"},
                {"Main.SearchPlaceholder", "Search projects, images, or stages"},
                {"Main.NewProject", "New Project"},
                {"Main.SidebarTitle", "Production Center"},
                {"Main.SidebarSubtitle", "Plan, generate, and manage visual assets across projects"},
                {"Main.Nav.ProjectHall", "Project Hall"},
                {"Main.Nav.TaskQueue", "Task Queue"},
                {"Main.Nav.MediaLibrary", "Media Library"},
                {"Main.Nav.SystemSettings", "System Settings"},
                {"Main.CurrentSummary", "Current Summary"},
                {"Main.Stat.Active", "Active"},
                {"Main.Stat.Generating", "Generating"},
                {"Main.Stat.Average", "Average"},
                {"Main.Footer.ProfessionalEdition", "Open Source Edition"},
                {"Workspace.Step.Import", "Import Assets"},
                {"Workspace.Step.Plan", "Generate Plan"},
                {"Workspace.Step.Render", "Batch Render"},
                {"Workspace.Step.Review", "Review & Export"},
                {"ProjectHall.Filter.All", "All Projects"},
                {"ProjectHall.Filter.Planning", "Planning"},
                {"ProjectHall.Filter.Rendering", "Rendering"},
                {"ProjectHall.Filter.Ready", "Ready"},
                {"ProjectHall.Filter.Failed", "Failed"},
                {"ProjectHall.Filter.Completed", "Completed"},
                {"ProjectHall.NoCover", "No cover image"},
                {"ProjectHall.RetryFailed", "Retry Failed"},
                {"Media.Filter.All", "All Media"},
                {"Media.Filter.Source", "Source Images"},
                {"Media.Filter.Generated", "Generated"},
                {"Media.Filter.Failed", "Failed"},
                {"Media.Action.OpenProject", "Open Project"},
                {"Media.Action.OpenFile", "Open File"},
                {"Media.Action.Download", "Download"},
                {"Media.Action.Preview", "Preview"},
                {"Media.Empty", "No media items match the current filters."},
                {"Media.NoPreview", "No preview"},
                {"Media.InlinePreview", "Preview"},
                {"Media.Title.UnnamedSource", "Untitled Source Image"},
                {"Media.Title.UnnamedGenerated", "Untitled Generated Image"},
                {"Media.Kind.Source", "Source"},
                {"Media.Kind.Generated", "Generated"},
                {"Media.Status.Imported", "Imported"},
                {"Upload.Title", "Reference Images"},
                {"Upload.Description", "Each project can keep up to 10 reference images."},
                {"Upload.Import", "Import Images"},
                {"Upload.Empty", "Import product images to start planning and generation."},
                {"Overview.Title", "Project Overview"},
                {"Overview.SourceCount", "Source Images"},
                {"Overview.PlanCount", "Planned Images"},
                {"PlanEditor.DesignTitle", "Design Plan Markdown"},
                {"PlanEditor.DesignDescription", "Edit the overall visual direction, palette, typography, and layout guidance here."},
                {"PlanEditor.ImageTitle", "Image Plan Markdown"},
                {"PlanEditor.ImageDescription", "Keep the Image N structure stable so single-image regeneration stays predictable."},
                {"Output.Title", "Output Gallery"},
                {"Output.Description", "Click a thumbnail to preview. Hover to download, edit, or regenerate the image."},
                {"Output.Placeholder", "Waiting for image"},
                {"Output.Action.Download", "Save"},
                {"Output.Action.Edit", "Edit"},
                {"Output.Action.Regenerate", "Retry"},
                {"Log.Title", "Activity Log"},
                {"Params.Title", "Parameters"},
                {"Params.Scenario", "Scenario"},
                {"Params.Requirements", "Requirements"},
                {"Params.TargetLanguage", "Target Language"},
                {"Params.PlannerProvider", "Planner Provider"},
                {"Params.PlannerModel", "Planner Model"},
                {"Params.ImageProvider", "Image Provider"},
                {"Params.ImageModel", "Image Model"},
                {"Params.AspectRatio", "Aspect Ratio"},
                {"Params.ImageSize", "Image Size"},
                {"Params.CustomSize", "Custom Image Size"},
                {"Params.GenerateCount", "Plan Count"},
                {"Params.DerivativeCount", "Derivative Count"},
                {"Params.AutoRun", "Auto Run"},
                {"Params.AutoRunDescription", "Automatically start rendering after planning completes"},
                {"Params.OpenOutput", "Open Output Folder"},
                {"Queue.Filter.All", "All Tasks"},
                {"Queue.Filter.Planning", "Planning"},
                {"Queue.Filter.Rendering", "Rendering"},
                {"Queue.Filter.Ready", "Ready"},
                {"Queue.Filter.Failed", "Failed"},
                {"Queue.Filter.Completed", "Completed"},
                {"Queue.Action.StartSelected", "Run Selected"},
                {"Queue.Action.RetryFiltered", "Retry Failed"},
                {"Queue.Action.StartSelectedCount", "Run Selected ({0})"},
                {"Queue.Action.RetryFilteredCount", "Retry Failed ({0})"},
                {"Queue.Stat.Running", "Running"},
                {"Queue.Stat.Planning", "Planning"},
                {"Queue.Stat.Failed", "Needs Retry"},
                {"Queue.Stat.Average", "Average Progress"},
                {"Queue.SelectAllTooltip", "Check to select all items in the current list. Uncheck to clear all."},
                {"Queue.Column.Title", "Project"},
                {"Queue.Column.Summary", "Summary"},
                {"Queue.Column.Scenario", "Scenario"},
                {"Queue.Column.Status", "Status"},
                {"Queue.Column.Progress", "Progress"},
                {"Queue.Column.Scale", "Scope"},
                {"Queue.Column.Auto", "Auto"},
                {"Queue.Column.QueueStatus", "Queue"},
                {"Queue.Column.Run", "Run"},
                {"Queue.Column.Open", "Open"},
                {"Queue.Column.Close", "Close"},
                {"Queue.Open", "Open"},
                {"Queue.Close", "Close"},
                {"Settings.Title.General", "General"},
                {"Settings.Language", "Language"},
                {"Settings.Theme", "Theme"},
                {"Settings.Tab.Models", "Model Settings"},
                {"Settings.Tab.Scenarios", "Scenario Templates"},
                {"Settings.Models.Title", "Model Settings"},
                {"Settings.Models.Description", "Configure the planning and image generation providers used by the studio."},
                {"Settings.Models.Save", "Save Model Settings"},
                {"Settings.Models.PlannerCard", "Planning Models"},
                {"Settings.Models.ImageCard", "Image Models"},
                {"Settings.Models.CurrentProvider", "Selected Provider"},
                {"Settings.Models.DeepSeekModel", "DeepSeek Model"},
                {"Settings.Models.QwenModel", "Qwen Model"},
                {"Settings.Models.DeepSeekBaseUrl", "DeepSeek Base URL"},
                {"Settings.Models.QwenBaseUrl", "Qwen Base URL"},
                {"Settings.Models.DeepSeekApiKey", "DeepSeek API Key"},
                {"Settings.Models.QwenApiKey", "Qwen API Key"},
                {"Settings.Models.OpenAiPlannerModel", "OpenAI Compatible Planner Model"},
                {"Settings.Models.OpenAiPlannerBaseUrl", "OpenAI Compatible Planner Base URL"},
                {"Settings.Models.OpenAiPlannerApiKey", "OpenAI Compatible Planner API Key"},
                {"Settings.Models.GeminiModel", "Gemini Model"},
                {"Settings.Models.GeminiApiKey", "Gemini API Key"},
                {"Settings.Models.GeminiAuthHint", "Leave Gemini API Key empty to use the Vertex settings from ModelProviders.local.json or ModelProviders.json."},
                {"Settings.Models.OpenAiImageModel", "OpenAI Compatible Image Model"},
                {"Settings.Models.OpenAiImageBaseUrl", "OpenAI Compatible Image Base URL"},
                {"Settings.Models.OpenAiImageApiKey", "OpenAI Compatible Image API Key"},
                {"Settings.Models.QwenImageEndpoint", "Qwen Image Endpoint"},
                {"Settings.Models.QwenImageApiKey", "Qwen Image API Key"},
                {"Settings.Models.PlannerHint", "The planner uses the selected provider below as the default route for new projects."},
                {"Settings.Models.ImageHint", "Qwen supports custom image sizes. Gemini uses the standard preset sizes."},
                {"Settings.Scenarios.Add", "Add Scenario"},
                {"Settings.Scenarios.Save", "Save Scenario"},
                {"Settings.Scenarios.Delete", "Delete Scenario"},
                {"Settings.Scenarios.Count", "Scenarios: {0}"},
                {"Settings.Scenarios.Name", "Name"},
                {"Settings.Scenarios.Description", "Description"},
                {"Settings.Scenarios.Type", "Type"},
                {"Settings.Scenarios.DetailTitle", "Scenario Template Details"},
                {"Settings.Scenarios.DetailDescription", "Use the upper editor for design planning guidance and the lower editor for image planning guidance."},
                {"Settings.Scenarios.DesignTemplate", "Design Planning Template"},
                {"Settings.Scenarios.ImageTemplate", "Image Planning Template"},
                {"Dialog.Settings", "System Settings"},
                {"Dialog.SaveScenarioSuccess", "Scenario template saved successfully."},
                {"Dialog.SaveScenarioFailed", "Failed to save scenario template"},
                {"Dialog.SaveModelSuccess", "Model settings saved successfully."},
                {"Dialog.SaveModelFailed", "Failed to save model settings"},
                {"Shell.Page.ProjectHall", "Project Hall"},
                {"Shell.Page.TaskQueue", "Task Queue"},
                {"Shell.Page.MediaLibrary", "Media Library"},
                {"Shell.Page.SystemSettings", "System Settings"},
                {"Shell.Page.Workspace", "Project Workspace"},
                {"Shell.Desc.WorkspaceEmpty", "Open a project from Project Hall or Task Queue to work with it here in tabs."},
                {"Shell.Desc.WorkspaceOpen", "{0} tabs open. Currently viewing {1}."},
                {"Shell.Desc.TaskQueue", "Track planning, rendering, and completion states for every project in one queue."},
                {"Shell.Desc.MediaLibrary", "{0} media items collected. Filter quickly by type, status, and keyword."},
                {"Shell.Desc.SystemSettings", "Manage providers, scenario templates, language, and default generation behavior."},
                {"Shell.Desc.ProjectHall", "{0} projects available. Planning and rendering can run in parallel."},
                {"Shell.WorkspaceDefaultTitle", "Project Workspace"},
                {"Shell.WorkspaceDefaultSubtitle", "Open projects from Project Hall or Task Queue to switch between them here."},
                {"Shell.WorkspaceTabsSummary", "{0} projects open"},
                {"Shell.StatusBar", "Active projects {0} | Rendering {1} | Average progress {2}"},
                {"Shell.Media.Success", "Success"},
                {"Shell.Media.Failed", "Failed"},
                {"Shell.Media.Missing", "Missing"},
                {"Shell.Media.Running", "Running"},
                {"Shell.Media.Pending", "Pending"},
                {"Shell.Dialog.DeleteScenario", "Delete Scenario"},
                {"Shell.Dialog.DeleteScenarioKeepOne", "At least one scenario template must remain."},
                {"Shell.Dialog.CloseProject", "Close Project"},
                {"Shell.Dialog.CloseProjectBusy", "{0} is still running. Closing it will stop the current task. Continue?"},
                {"Shell.Dialog.TaskExecutionFailed", "Task execution failed"},
                {"Shell.Dialog.RetryFailedImages", "Retry failed images failed"},
                {"Shell.Dialog.PlanFailed", "Planning failed"},
                {"Shell.Dialog.RenderFailed", "Image generation failed"},
                {"Shell.Dialog.RegenerateFailed", "Regeneration failed"},
                {"Shell.Dialog.OpenOutput", "Open Output Folder"},
                {"Shell.Dialog.NoSelectedProject", "No project is currently selected."},
                {"Shell.Dialog.NoOutputFolder", "This project does not have an output folder yet. Generate images first."},
                {"Shell.Dialog.OpenOutputFailed", "Failed to open output folder: {0}"},
                {"Project.DefaultSummary", "No project summary yet"},
                {"Project.DefaultName", "Project {0}"},
                {"Project.NoText", "No Text"},
                {"Project.AssetCount", "{0} assets"},
                {"Project.SourceSummary", "{0} source / {1} planned / {2} outputs"},
                {"Project.SelectedModels", "Planner: {0} | Image: {1}"},
                {"Project.Badge.Image", "Img {0}"},
                {"Project.Resolution.Quality", "Image Size"},
                {"Project.Resolution.OutputSize", "Output Size"},
                {"Project.Stage.Planning", "Planning"},
                {"Project.Stage.Rendering", "Rendering"},
                {"Project.Stage.ReadyToRender", "Ready To Render"},
                {"Project.Stage.ReadyToPlan", "Ready To Plan"},
                {"Project.Stage.Idle", "Idle"},
                {"Project.Failure.None", "No issues"},
                {"Project.Updated.JustNow", "Updated just now"},
                {"Project.Updated.Minutes", "{0} min ago"},
                {"Project.Updated.Hours", "{0} hr ago"},
                {"Project.Updated.Days", "{0} day(s) ago"},
                {"Project.Queue.Planning", "Planning"},
                {"Project.Queue.Processing", "Processing"},
                {"Project.Queue.RetryFailed", "Failed, retry needed"},
                {"Project.Queue.Completed", "Completed"},
                {"Project.Queue.Waiting", "Waiting"},
                {"Project.Queue.Empty", "--"},
                {"Project.Action.Stop", "Stop"},
                {"Project.Action.RetryFailed", "Retry Failed"},
                {"Project.Action.StartRender", "Start Rendering"},
                {"Project.Action.StartPlan", "Start Planning"},
                {"Project.Action.Open", "Open"},
                {"Project.CustomSizeHint", "Example: 1536*1024. Total pixels must stay between 512*512 and 2048*2048."},
                {"Project.FixedSizeHint", "Gemini preset sizes: 1K, 2K, 4K."}
            }

            Dim zh = New Dictionary(Of String, String)(StringComparer.OrdinalIgnoreCase) From {
                {"App.Name", "MediaFactory"},
                {"Main.SearchPlaceholder", "搜索项目、图片或阶段"},
                {"Main.NewProject", "新建项目"},
                {"Main.SidebarTitle", "生产中心"},
                {"Main.SidebarSubtitle", "在多个项目间统一规划、出图与管理素材"},
                {"Main.Nav.ProjectHall", "项目大厅"},
                {"Main.Nav.TaskQueue", "任务队列"},
                {"Main.Nav.MediaLibrary", "图片库"},
                {"Main.Nav.SystemSettings", "系统设置"},
                {"Main.CurrentSummary", "当前摘要"},
                {"Main.Stat.Active", "活跃"},
                {"Main.Stat.Generating", "生成中"},
                {"Main.Stat.Average", "平均"},
                {"Main.Footer.ProfessionalEdition", "开源版"},
                {"Workspace.Step.Import", "导入素材"},
                {"Workspace.Step.Plan", "生成规划"},
                {"Workspace.Step.Render", "批量出图"},
                {"Workspace.Step.Review", "复核导出"},
                {"ProjectHall.Filter.All", "全部项目"},
                {"ProjectHall.Filter.Planning", "规划中"},
                {"ProjectHall.Filter.Rendering", "生成中"},
                {"ProjectHall.Filter.Ready", "待出图"},
                {"ProjectHall.Filter.Failed", "失败待处理"},
                {"ProjectHall.Filter.Completed", "已完成"},
                {"ProjectHall.NoCover", "暂无项目封面"},
                {"ProjectHall.RetryFailed", "重试失败"},
                {"Media.Filter.All", "全部媒体"},
                {"Media.Filter.Source", "源图"},
                {"Media.Filter.Generated", "成品图"},
                {"Media.Filter.Failed", "失败图"},
                {"Media.Action.OpenProject", "打开项目"},
                {"Media.Action.OpenFile", "打开文件"},
                {"Media.Action.Download", "下载文件"},
                {"Media.Action.Preview", "预览图片"},
                {"Media.Empty", "当前没有符合筛选条件的图片。"},
                {"Media.NoPreview", "暂无预览"},
                {"Media.InlinePreview", "预览"},
                {"Media.Title.UnnamedSource", "未命名源图"},
                {"Media.Title.UnnamedGenerated", "未命名成品图"},
                {"Media.Kind.Source", "源图"},
                {"Media.Kind.Generated", "成品图"},
                {"Media.Status.Imported", "已导入"},
                {"Upload.Title", "产品图"},
                {"Upload.Description", "每个项目最多保留 10 张参考图。"},
                {"Upload.Import", "导入图片"},
                {"Upload.Empty", "导入产品图后即可开始规划和生成。"},
                {"Overview.Title", "项目概览"},
                {"Overview.SourceCount", "源图数量"},
                {"Overview.PlanCount", "规划数量"},
                {"PlanEditor.DesignTitle", "设计规划 Markdown"},
                {"PlanEditor.DesignDescription", "在这里编辑整体风格、配色、字体和版式指导。"},
                {"PlanEditor.ImageTitle", "图片规划 Markdown"},
                {"PlanEditor.ImageDescription", "保持 Image N 结构稳定，便于后续逐张重生成。"},
                {"Output.Title", "输出画廊"},
                {"Output.Description", "单击缩略图预览，悬停可下载、编辑或重生成。"},
                {"Output.Placeholder", "等待图片"},
                {"Output.Action.Download", "下载"},
                {"Output.Action.Edit", "编辑"},
                {"Output.Action.Regenerate", "重生成"},
                {"Log.Title", "后台日志"},
                {"Params.Title", "参数配置"},
                {"Params.Scenario", "业务场景"},
                {"Params.Requirements", "需求说明"},
                {"Params.TargetLanguage", "目标语言"},
                {"Params.PlannerProvider", "规划供应商"},
                {"Params.PlannerModel", "规划模型"},
                {"Params.ImageProvider", "绘图供应商"},
                {"Params.ImageModel", "绘图模型"},
                {"Params.AspectRatio", "尺寸比例"},
                {"Params.ImageSize", "出图规格"},
                {"Params.CustomSize", "自定义尺寸"},
                {"Params.GenerateCount", "规划数量"},
                {"Params.DerivativeCount", "衍生数量"},
                {"Params.AutoRun", "自动执行"},
                {"Params.AutoRunDescription", "规划完成后自动开始生成图片"},
                {"Params.OpenOutput", "打开输出目录"},
                {"Queue.Filter.All", "全部任务"},
                {"Queue.Filter.Planning", "规划中"},
                {"Queue.Filter.Rendering", "生成中"},
                {"Queue.Filter.Ready", "待出图"},
                {"Queue.Filter.Failed", "失败待处理"},
                {"Queue.Filter.Completed", "已完成"},
                {"Queue.Action.StartSelected", "启动选中项"},
                {"Queue.Action.RetryFiltered", "重试失败项"},
                {"Queue.Action.StartSelectedCount", "启动选中项（{0}）"},
                {"Queue.Action.RetryFilteredCount", "重试失败项（{0}）"},
                {"Queue.Stat.Running", "执行中"},
                {"Queue.Stat.Planning", "规划中"},
                {"Queue.Stat.Failed", "失败待处理"},
                {"Queue.Stat.Average", "平均进度"},
                {"Queue.SelectAllTooltip", "勾选可全选当前列表，取消勾选可清空选择。"},
                {"Queue.Column.Title", "项目标题"},
                {"Queue.Column.Summary", "摘要"},
                {"Queue.Column.Scenario", "场景"},
                {"Queue.Column.Status", "状态"},
                {"Queue.Column.Progress", "进度"},
                {"Queue.Column.Scale", "规模"},
                {"Queue.Column.Auto", "自动"},
                {"Queue.Column.QueueStatus", "队列状态"},
                {"Queue.Column.Run", "执行"},
                {"Queue.Column.Open", "打开"},
                {"Queue.Column.Close", "关闭"},
                {"Queue.Open", "打开"},
                {"Queue.Close", "关闭"},
                {"Settings.Title.General", "通用设置"},
                {"Settings.Language", "界面语言"},
                {"Settings.Theme", "主题"},
                {"Settings.Tab.Models", "模型配置"},
                {"Settings.Tab.Scenarios", "场景模板"},
                {"Settings.Models.Title", "模型配置"},
                {"Settings.Models.Description", "配置工作台使用的规划和绘图模型供应商。"},
                {"Settings.Models.Save", "保存模型配置"},
                {"Settings.Models.PlannerCard", "规划模型"},
                {"Settings.Models.ImageCard", "绘图模型"},
                {"Settings.Models.CurrentProvider", "当前供应商"},
                {"Settings.Models.DeepSeekModel", "DeepSeek 模型"},
                {"Settings.Models.QwenModel", "Qwen 模型"},
                {"Settings.Models.DeepSeekBaseUrl", "DeepSeek Base URL"},
                {"Settings.Models.QwenBaseUrl", "Qwen Base URL"},
                {"Settings.Models.DeepSeekApiKey", "DeepSeek API Key"},
                {"Settings.Models.QwenApiKey", "Qwen API Key"},
                {"Settings.Models.OpenAiPlannerModel", "OpenAI 兼容规划模型"},
                {"Settings.Models.OpenAiPlannerBaseUrl", "OpenAI 兼容规划 Base URL"},
                {"Settings.Models.OpenAiPlannerApiKey", "OpenAI 兼容规划 API Key"},
                {"Settings.Models.GeminiModel", "Gemini 模型"},
                {"Settings.Models.GeminiApiKey", "Gemini API Key"},
                {"Settings.Models.GeminiAuthHint", "如果 Gemini API Key 留空，系统会使用 ModelProviders.local.json 或 ModelProviders.json 中的 Vertex 配置。"},
                {"Settings.Models.OpenAiImageModel", "OpenAI 兼容生图模型"},
                {"Settings.Models.OpenAiImageBaseUrl", "OpenAI 兼容生图 Base URL"},
                {"Settings.Models.OpenAiImageApiKey", "OpenAI 兼容生图 API Key"},
                {"Settings.Models.QwenImageEndpoint", "Qwen 图片接口"},
                {"Settings.Models.QwenImageApiKey", "Qwen 图片 API Key"},
                {"Settings.Models.PlannerHint", "新项目默认使用这里选中的规划供应商。"},
                {"Settings.Models.ImageHint", "Qwen 支持自定义尺寸，Gemini 使用预设规格。"},
                {"Settings.Scenarios.Add", "新增场景"},
                {"Settings.Scenarios.Save", "保存场景"},
                {"Settings.Scenarios.Delete", "删除场景"},
                {"Settings.Scenarios.Count", "场景数量：{0}"},
                {"Settings.Scenarios.Name", "名称"},
                {"Settings.Scenarios.Description", "描述"},
                {"Settings.Scenarios.Type", "Type"},
                {"Settings.Scenarios.DetailTitle", "场景模板详情"},
                {"Settings.Scenarios.DetailDescription", "上方编辑设计规划模板，下方编辑图片规划模板。"},
                {"Settings.Scenarios.DesignTemplate", "设计规划模板"},
                {"Settings.Scenarios.ImageTemplate", "图片规划模板"},
                {"Dialog.Settings", "系统设置"},
                {"Dialog.SaveScenarioSuccess", "场景模板保存成功。"},
                {"Dialog.SaveScenarioFailed", "保存场景模板失败"},
                {"Dialog.SaveModelSuccess", "模型配置保存成功。"},
                {"Dialog.SaveModelFailed", "保存模型配置失败"},
                {"Shell.Page.ProjectHall", "项目大厅"},
                {"Shell.Page.TaskQueue", "任务队列"},
                {"Shell.Page.MediaLibrary", "图片库"},
                {"Shell.Page.SystemSettings", "系统设置"},
                {"Shell.Page.Workspace", "项目工作区"},
                {"Shell.Desc.WorkspaceEmpty", "从项目大厅或任务队列打开项目后，可在这里通过标签页切换。"},
                {"Shell.Desc.WorkspaceOpen", "已打开 {0} 个标签页，当前查看 {1}。"},
                {"Shell.Desc.TaskQueue", "集中查看所有项目的规划、渲染与完成状态。"},
                {"Shell.Desc.MediaLibrary", "已汇总 {0} 个媒体项，可按类型、状态和关键词快速筛选。"},
                {"Shell.Desc.SystemSettings", "统一管理模型供应商、场景模板、语言与默认生成策略。"},
                {"Shell.Desc.ProjectHall", "当前共有 {0} 个项目，可并行执行规划与出图。"},
                {"Shell.WorkspaceDefaultTitle", "项目工作区"},
                {"Shell.WorkspaceDefaultSubtitle", "从项目大厅或任务队列打开项目，即可在这里通过标签页切换项目。"},
                {"Shell.WorkspaceTabsSummary", "已打开 {0} 个项目"},
                {"Shell.StatusBar", "活跃项目 {0} | 生成中 {1} | 平均进度 {2}"},
                {"Shell.Media.Success", "成功"},
                {"Shell.Media.Failed", "失败"},
                {"Shell.Media.Missing", "缺失"},
                {"Shell.Media.Running", "运行中"},
                {"Shell.Media.Pending", "待生成"},
                {"Shell.Dialog.DeleteScenario", "删除场景"},
                {"Shell.Dialog.DeleteScenarioKeepOne", "至少需要保留一个场景模板。"},
                {"Shell.Dialog.CloseProject", "关闭项目"},
                {"Shell.Dialog.CloseProjectBusy", "{0} 仍在运行，关闭后将停止当前任务。是否继续？"},
                {"Shell.Dialog.TaskExecutionFailed", "任务执行失败"},
                {"Shell.Dialog.RetryFailedImages", "重试失败图片失败"},
                {"Shell.Dialog.PlanFailed", "规划失败"},
                {"Shell.Dialog.RenderFailed", "出图失败"},
                {"Shell.Dialog.RegenerateFailed", "重生成失败"},
                {"Shell.Dialog.OpenOutput", "打开输出目录"},
                {"Shell.Dialog.NoSelectedProject", "当前没有选中的项目。"},
                {"Shell.Dialog.NoOutputFolder", "当前项目还没有输出目录，请先生成图片。"},
                {"Shell.Dialog.OpenOutputFailed", "无法打开输出目录：{0}"},
                {"Project.DefaultSummary", "暂无项目摘要"},
                {"Project.DefaultName", "项目 {0}"},
                {"Project.NoText", "无文字"},
                {"Project.AssetCount", "{0} 个资产"},
                {"Project.SourceSummary", "{0} 张源图 / {1} 张规划 / {2} 张输出"},
                {"Project.SelectedModels", "规划模型：{0} | 绘图模型：{1}"},
                {"Project.Badge.Image", "图{0}"},
                {"Project.Resolution.Quality", "出图规格"},
                {"Project.Resolution.OutputSize", "输出尺寸"},
                {"Project.Stage.Planning", "规划中"},
                {"Project.Stage.Rendering", "生成中"},
                {"Project.Stage.ReadyToRender", "待出图"},
                {"Project.Stage.ReadyToPlan", "待规划"},
                {"Project.Stage.Idle", "空闲"},
                {"Project.Failure.None", "无异常"},
                {"Project.Updated.JustNow", "刚刚更新"},
                {"Project.Updated.Minutes", "{0} 分钟前"},
                {"Project.Updated.Hours", "{0} 小时前"},
                {"Project.Updated.Days", "{0} 天前"},
                {"Project.Queue.Planning", "规划中"},
                {"Project.Queue.Processing", "处理中"},
                {"Project.Queue.RetryFailed", "失败待重试"},
                {"Project.Queue.Completed", "已完成"},
                {"Project.Queue.Waiting", "等待执行"},
                {"Project.Queue.Empty", "--"},
                {"Project.Action.Stop", "停止"},
                {"Project.Action.RetryFailed", "重试失败"},
                {"Project.Action.StartRender", "启动生图"},
                {"Project.Action.StartPlan", "启动规划"},
                {"Project.Action.Open", "打开"},
                {"Project.CustomSizeHint", "示例：1536*1024，总像素需在 512*512 到 2048*2048 之间。"},
                {"Project.FixedSizeHint", "Gemini 预设规格：1K、2K、4K。"}
            }

            Return New Dictionary(Of String, IReadOnlyDictionary(Of String, String))(StringComparer.OrdinalIgnoreCase) From {
                {"en", en},
                {"zh-CN", zh}
            }
        End Function
    End Class
End Namespace
